# Generated by Django 4.2.4 on 2023-08-08 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ManyToManyField(to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(blank=True, to='auctions.comment'),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
