# Generated by Django 4.2.4 on 2023-08-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
